// <auto-generated />
namespace CadastroCliente.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class aumenta_endereco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aumenta_endereco));
        
        string IMigrationMetadata.Id
        {
            get { return "201903221630303_aumenta_endereco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
